/// 仿造 高清 超清的概念 ， 2倍图叫HD，3倍图叫UD
export const HDImageResources = [
  ['background', 'res/background@2x.png'],
  ['player', 'res/player@2x.png'],
  ['bullet', 'res/bullet@2x.png'],
  ['bullet2', 'res/bullet2@2x.png'],
  ['enemyBullet2', 'res/enemybullet/enemybullet2@2x.png'],
  ['boss1', 'res/boss/boss1@2x.png'],
  ['boss2', 'res/boss/boss2@2x.png'],
  ['boss3', 'res/boss/boss3@2x.png'],
  ['boss4', 'res/boss/boss4@2x.png'],
  ['boss5', 'res/boss/boss5@2x.png'],
  ['boss6', 'res/boss/boss6@2x.png'],
  ['boss7', 'res/boss/boss7@2x.png'],
  ['boss8', 'res/boss/boss8@2x.png'],
  ['bubble', 'res/bubble@2x.png'],
  ['littleAttack1', 'res/littleAttack/littleAttack1@2x.png'],
  ['littleAttack2', 'res/littleAttack/littleAttack2@2x.png'],
  ['UFO1', 'res/ufo/ufo1@2x.png'],
  ['UFO2', 'res/ufo/ufo2@2x.png'],
  ['UFO3', 'res/ufo/ufo3@2x.png'],
  ['UFO4', 'res/ufo/ufo4@2x.png'],
  ['UFO5', 'res/ufo/ufo5@2x.png'],
  ['UFO6', 'res/ufo/ufo6@2x.png'],
  ['stone1', 'res/stone/stone1@2x.png'],
  ['stone2', 'res/stone/stone2@2x.png'],
  ['stone3', 'res/stone/stone3@2x.png'],
  ['stone4', 'res/stone/stone4@2x.png'],
  ['stone5', 'res/stone/stone5@2x.png'],
  ['stone6', 'res/stone/stone6@2x.png'],
  ['stone7', 'res/stone/stone7@2x.png'],
  ['stone8', 'res/stone/stone8@2x.png'],
  ['stone9', 'res/stone/stone9@2x.png'],
  ['stone10', 'res/stone/stone10@2x.png'],
  ['stone11', 'res/stone/stone11@2x.png'],
  ['stone12', 'res/stone/stone12@2x.png'],
  ['spaceship1', 'res/spaceship/spaceship1@2x.png'],
  ['spaceship2', 'res/spaceship/spaceship2@2x.png'],
  ['spaceship3', 'res/spaceship/spaceship3@2x.png'],
  ['spaceship4', 'res/spaceship/spaceship4@2x.png'],
  ['spaceship5', 'res/spaceship/spaceship5@2x.png'],
  ['spaceship6', 'res/spaceship/spaceship6@2x.png'],
  ['spaceship7', 'res/spaceship/spaceship7@2x.png'],
  ['spaceship8', 'res/spaceship/spaceship8@2x.png'],
  ['spaceship9', 'res/spaceship/spaceship9@2x.png'],
  ['spaceship10', 'res/spaceship/spaceship10@2x.png'],
  ['spaceship11', 'res/spaceship/spaceship11@2x.png'],
  ['spaceship12', 'res/spaceship/spaceship12@2x.png'],
  ['followplane1', 'res/followplane/followplane1@2x.png'],
  ['followplane2', 'res/followplane/followplane2@2x.png'],
  ['followplane3', 'res/followplane/followplane3@2x.png'],
  ['explosion1', 'res/explosion1@2x.png'],
  ['explosion2', 'res/explosion2@2x.png'],
  ['explosion3', 'res/explosion3@2x.png'],
  ['explosion4', 'res/explosion4@2x.png'],
  ['explosion5', 'res/explosion5@2x.png'],
  ['explosion6', 'res/explosion6@2x.png'],
  ['explosion7', 'res/explosion7@2x.png'],
  ['explosion8', 'res/explosion8@2x.png'],
  ['explosion9', 'res/explosion9@2x.png'],
  ['explosion10', 'res/explosion10@2x.png'],
  ['explosion11', 'res/explosion11@2x.png'],
  ['explosion12', 'res/explosion12@2x.png'],
  ['explosion13', 'res/explosion13@2x.png'],
  ['explosion14', 'res/explosion14@2x.png'],
  ['explosion15', 'res/explosion15@2x.png'],
  ['explosion16', 'res/explosion16@2x.png'],
  ['explosion17', 'res/explosion17@2x.png'],
  ['explosion18', 'res/explosion18@2x.png'],
];

export const UDImageResources = [
  ['background', 'res/background@3x.png'],
  ['player', 'res/player@3x.png'],
  ['bullet', 'res/bullet@3x.png'],
  ['bullet2', 'res/bullet2@3x.png'],
  ['enemyBullet2', 'res/enemybullet/enemybullet2@3x.png'],
  ['boss1', 'res/boss/boss1@3x.png'],
  ['boss2', 'res/boss/boss2@3x.png'],
  ['boss3', 'res/boss/boss3@3x.png'],
  ['boss4', 'res/boss/boss4@3x.png'],
  ['boss5', 'res/boss/boss5@3x.png'],
  ['boss6', 'res/boss/boss6@3x.png'],
  ['boss7', 'res/boss/boss7@3x.png'],
  ['boss8', 'res/boss/boss8@3x.png'],
  ['bubble', 'res/bubble@3x.png'],
  ['littleAttack1', 'res/littleAttack/littleAttack1@3x.png'],
  ['littleAttack2', 'res/littleAttack/littleAttack2@3x.png'],
  ['UFO1', 'res/ufo/ufo1@3x.png'],
  ['UFO2', 'res/ufo/ufo2@3x.png'],
  ['UFO3', 'res/ufo/ufo3@3x.png'],
  ['UFO4', 'res/ufo/ufo4@3x.png'],
  ['UFO5', 'res/ufo/ufo5@3x.png'],
  ['UFO6', 'res/ufo/ufo6@3x.png'],
  ['stone1', 'res/stone/stone1@3x.png'],
  ['stone2', 'res/stone/stone2@3x.png'],
  ['stone3', 'res/stone/stone3@3x.png'],
  ['stone4', 'res/stone/stone4@3x.png'],
  ['stone5', 'res/stone/stone5@3x.png'],
  ['stone6', 'res/stone/stone6@3x.png'],
  ['stone7', 'res/stone/stone7@3x.png'],
  ['stone8', 'res/stone/stone8@3x.png'],
  ['stone9', 'res/stone/stone9@3x.png'],
  ['stone10', 'res/stone/stone10@2x.png'],
  ['stone11', 'res/stone/stone11@2x.png'],
  ['stone12', 'res/stone/stone12@2x.png'],
  ['spaceship1', 'res/spaceship/spaceship1@3x.png'],
  ['spaceship2', 'res/spaceship/spaceship2@3x.png'],
  ['spaceship3', 'res/spaceship/spaceship3@3x.png'],
  ['spaceship4', 'res/spaceship/spaceship4@3x.png'],
  ['spaceship5', 'res/spaceship/spaceship5@3x.png'],
  ['spaceship6', 'res/spaceship/spaceship6@3x.png'],
  ['spaceship7', 'res/spaceship/spaceship7@3x.png'],
  ['spaceship8', 'res/spaceship/spaceship8@3.png'],
  ['spaceship9', 'res/spaceship/spaceship9@3x.png'],
  ['spaceship10', 'res/spaceship/spaceship10@3x.png'],
  ['spaceship11', 'res/spaceship/spaceship11@3x.png'],
  ['spaceship12', 'res/spaceship/spaceship12@3x.png'],
  ['followplane1', 'res/followplane/followplane1@3x.png'],
  ['followplane2', 'res/followplane/followplane2@3x.png'],
  ['followplane3', 'res/followplane/followplane3@3x.png'],


];

export const AudioResources = {
  biu: 'res/biu.mp3',
  bgm: 'res/bgm.mp3'
};

export const ChineseResources = {
  ziku: 'res/ziku.json'
};